<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:stl="http://pisa.intecs.it/stl" xmlns:tbx="http://pisa.intecs.it/mass/toolbox/xmlScript" version="2.0">
	<xsl:template match="model">
<xsl:apply-templates select="generalConstant"/>
<!--File generated by the Feed via Velocity-->
<rep:metadataReport version="1.2" xmlns:rep="http://ngeo.eo.esa.int/schema/metadataReport" 
xmlns:alt="http://www.opengis.net/alt/2.0" 
xmlns:eop="http://www.opengis.net/eop/2.0" 
xmlns:gml="http://www.opengis.net/gml/3.2" 
xmlns:om="http://www.opengis.net/om/2.0"  
xmlns:xlink="http://www.w3.org/1999/xlink" 
xmlns:ows="http://www.opengis.net/ows/2.0" 
xmlns:sar="http://www.opengis.net/sar/2.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <rep:reportType>ARCHIVING</rep:reportType>
 <rep:dateTime>$date.get('yyyy-M-d')T$date.get('H:m:s')Z</rep:dateTime>
##This is the replacementHeader
 <rep:replacementHeader>
    <rep:beginDate>$PERIOD_START</rep:beginDate>
    <rep:endDate>$PERIOD_END</rep:endDate>
    <rep:dateType><xsl:call-template name="extract"><xsl:with-param name="attribute" select="attribute[@id='dateType']"/></xsl:call-template></rep:dateType>
    <rep:targetProductType>
        <rep:platformShortName><xsl:call-template name="extract"><xsl:with-param name="attribute" select="attribute[@id='platformShortName']"/></xsl:call-template></rep:platformShortName>
        <rep:instrumentShortName><xsl:call-template name="extract"><xsl:with-param name="attribute" select="attribute[@id='instrumentShortName']"/></xsl:call-template></rep:instrumentShortName>
        <rep:operationalMode><xsl:call-template name="extract"><xsl:with-param name="attribute" select="attribute[@id='operationalMode']"/></xsl:call-template></rep:operationalMode>
        <rep:productType><xsl:call-template name="extract"><xsl:with-param name="attribute" select="attribute[@id='productType']"/></xsl:call-template></rep:productType>
    </rep:targetProductType>
</rep:replacementHeader> 
#foreach( $metadata in $metadataList )
 <sar:EarthObservation gml:id="ID_$velocityCount">
   <om:phenomenonTime>
     <gml:TimePeriod gml:id="tp_$velocityCount">
       <gml:beginPosition><xsl:apply-templates select="attribute[@id='beginAcquisition']"/></gml:beginPosition>
       <gml:endPosition><xsl:apply-templates select="attribute[@id='endAcquisition']"/></gml:endPosition>
     </gml:TimePeriod>
   </om:phenomenonTime>
   <om:resultTime>
     <gml:TimeInstant gml:id="archivingdate_$velocityCount">
       <gml:timePosition><xsl:apply-templates select="attribute[@id='availabilityTime']"/></gml:timePosition>
     </gml:TimeInstant>
   </om:resultTime>
   <om:procedure>
     <eop:EarthObservationEquipment gml:id="eoe_$velocityCount">
       <eop:platform>
         <eop:Platform>
           <eop:shortName><xsl:apply-templates select="attribute[@id='platformShortName']"/></eop:shortName>
			<xsl:if test="attribute[@id='platformSerialIdentifier'] != ''">
			   <eop:serialIdentifier><xsl:apply-templates select="attribute[@id='platformSerialIdentifier']"/></eop:serialIdentifier>		
			</xsl:if>    
         </eop:Platform>
       </eop:platform>
       <eop:instrument>
         <eop:Instrument>
           <eop:shortName>ASAR</eop:shortName>
         </eop:Instrument>
       </eop:instrument>
       <eop:sensor>
         <eop:Sensor>
			<xsl:if test="attribute[@id='sensorType'] != ''">
			   <eop:sensorType><xsl:apply-templates select="attribute[@id='sensorType']"/></eop:sensorType>		
			</xsl:if>    
           <eop:operationalMode codeSpace="any:sensorMode"><xsl:apply-templates select="attribute[@id='operationalMode']"/></eop:operationalMode>
			<xsl:if test="attribute[@id='swathIdentifier'] != ''">
			   <eop:swathIdentifier><xsl:apply-templates select="attribute[@id='swathIdentifier']"/></eop:swathIdentifier>		
			</xsl:if>    
         </eop:Sensor>
       </eop:sensor>
       <!-- we should include here an IF to check if at least one of the element is included in the config file-->
       <eop:acquisitionParameters>
         <sar:Acquisition>
			<xsl:if test="attribute[@id='orbitNumber'] != ''">
			   <eop:orbitNumber><xsl:apply-templates select="attribute[@id='orbitNumber']"/></eop:orbitNumber>		
			</xsl:if>    
			<xsl:if test="attribute[@id='orbitDirection'] != ''">
			   <eop:orbitDirection><xsl:apply-templates select="attribute[@id='orbitDirection']"/></eop:orbitDirection>		
			</xsl:if>    
			<xsl:if test="attribute[@id='wrsLongitudeGrid'] != ''">
			   <eop:wrsLongitudeGrid codeSpace=""><xsl:apply-templates select="attribute[@id='wrsLongitudeGrid']"/></eop:wrsLongitudeGrid>		
			</xsl:if>    
			<xsl:if test="attribute[@id='wrsLatitudeGrid'] != ''">
			   <eop:wrsLatitudeGrid codeSpace=""><xsl:apply-templates select="attribute[@id='wrsLatitudeGrid']"/></eop:wrsLatitudeGrid>		
			</xsl:if>    
			<xsl:if test="attribute[@id='startTimeFromAscendingNode'] != ''">
			   <eop:startTimeFromAscendingNode uom="ms"><xsl:apply-templates select="attribute[@id='startTimeFromAscendingNode']"/></eop:startTimeFromAscendingNode>		
			</xsl:if>    
			<xsl:if test="attribute[@id='completionTimeFromAscendingNode'] != ''">
			   <eop:completionTimeFromAscendingNode uom="ms"><xsl:apply-templates select="attribute[@id='completionTimeFromAscendingNode']"/></eop:completionTimeFromAscendingNode>		
			</xsl:if>    
			<xsl:if test="attribute[@id='illuminationAzimuthAngle'] != ''">
				   <eop:illuminationAzimuthAngle><xsl:apply-templates select="attribute[@id='illuminationAzimuthAngle']"/></eop:illuminationAzimuthAngle>
			</xsl:if> 
			<xsl:if test="attribute[@id='illuminationZenithAngle'] != ''">
				   <eop:illuminationZenithAngle><xsl:apply-templates select="attribute[@id='illuminationZenithAngle']"/></eop:illuminationZenithAngle>
			</xsl:if> 
			<xsl:if test="attribute[@id='illuminationElevationAngle'] != ''">
				   <eop:illuminationElevationAngle><xsl:apply-templates select="attribute[@id='illuminationElevationAngle']"/></eop:illuminationElevationAngle>
			</xsl:if> 
			 <!-- THIS IS SPECIFIC FOR THE SAR-->
			<xsl:if test="attribute[@id='polarisationMode'] != ''">
				   <sar:polarisationMode><xsl:apply-templates select="attribute[@id='polarisationMode']"/></sar:polarisationMode>
			</xsl:if>    
			<xsl:if test="attribute[@id='polarisationChannels'] != ''">
				   <sar:polarisationChannels><xsl:apply-templates select="attribute[@id='polarisationChannels']"/></sar:polarisationChannels>
			</xsl:if>    
			<xsl:if test="attribute[@id='antennaLookDirection'] != ''">
				   <sar:antennaLookDirection><xsl:apply-templates select="attribute[@id='antennaLookDirection']"/></sar:antennaLookDirection>
			</xsl:if>    
			<xsl:if test="attribute[@id='minimumIncidenceAngle'] != ''">
				   <sar:minimumIncidenceAngle><xsl:apply-templates select="attribute[@id='minimumIncidenceAngle']"/></sar:minimumIncidenceAngle>
			</xsl:if>    
			<xsl:if test="attribute[@id='maximumIncidenceAngle'] != ''">
				   <sar:maximumIncidenceAngle><xsl:apply-templates select="attribute[@id='maximumIncidenceAngle']"/></sar:maximumIncidenceAngle>
			</xsl:if>    
			<xsl:if test="attribute[@id='incidenceAngleVariation'] != ''">
				   <sar:incidenceAngleVariation><xsl:apply-templates select="attribute[@id='incidenceAngleVariation']"/></sar:incidenceAngleVariation>
			</xsl:if>    
			<xsl:if test="attribute[@id='dopplerFrequency'] != ''">
				   <sar:dopplerFrequency><xsl:apply-templates select="attribute[@id='dopplerFrequency']"/></sar:dopplerFrequency>
			</xsl:if>    
         </sar:Acquisition>
       </eop:acquisitionParameters>
     </eop:EarthObservationEquipment>
   </om:procedure>
   <om:observedProperty nilReason="inapplicable"/>
   <om:featureOfInterest>
     <eop:Footprint gml:id="fp_$velocityCount">
       <eop:multiExtentOf>
         <gml:MultiSurface gml:id="ms_$velocityCount" srsName="EPSG:4326">
           <gml:surfaceMembers>
             <gml:Polygon gml:id="fppoly_3">
               <gml:exterior>
                 <gml:LinearRing>
                   <gml:posList><xsl:apply-templates select="attribute[@id='footprint']"/></gml:posList>
                 </gml:LinearRing>
               </gml:exterior>
             </gml:Polygon>
           </gml:surfaceMembers>
         </gml:MultiSurface>
       </eop:multiExtentOf>
     </eop:Footprint>
   </om:featureOfInterest>
   <om:result>
     <eop:EarthObservationResult gml:id="eor_$velocityCount">
       <eop:product>
         <eop:ProductInformation>
           <eop:fileName>
             <ows:ServiceReference xlink:href="">
				<xsl:attribute name="xlink:href"><xsl:apply-templates select="attribute[@id='productURI']"/></xsl:attribute>
               <ows:RequestMessage/>
             </ows:ServiceReference>
           </eop:fileName>
			<!-- CHECK IF THIS IS THE RIGHT POSITION-->
			<xsl:if test="attribute[@id='productVersion'] != ''">
			   <eop:version><xsl:apply-templates select="attribute[@id='productVersion']"/></eop:version>		
			</xsl:if>  
			<!-- CHECK IF THIS IS THE RIGHT POSITION-->			
			<xsl:if test="attribute[@id='productSize'] != ''">
			   <eop:size><xsl:apply-templates select="attribute[@id='productSize']"/></eop:size>		
			</xsl:if>  			
         </eop:ProductInformation>
       </eop:product>
     </eop:EarthObservationResult>
   </om:result>
   <eop:metaDataProperty>
     <eop:EarthObservationMetaData>
       <eop:identifier><xsl:apply-templates select="attribute[@id='productId']"/></eop:identifier>
		<xsl:if test="attribute[@id='parentIdentifier'] !=''">
		   <eop:parentIdentifier><xsl:apply-templates select="attribute[@id='parentIdentifier']"/></eop:parentIdentifier>
		</xsl:if>
       <eop:acquisitionType><xsl:apply-templates select="attribute[@id='acquisitionType']"/></eop:acquisitionType>
		<xsl:if test="attribute[@id='acquisitionSubType'] !=''">
		   <eop:acquisitionSubType><xsl:apply-templates select="attribute[@id='acquisitionSubType']"/></eop:acquisitionSubType>
		</xsl:if>
       <eop:productType><xsl:apply-templates select="attribute[@id='productType']"/></eop:productType>
       <eop:status><xsl:apply-templates select="attribute[@id='status']"/></eop:status>
		<xsl:if test="attribute[@id='imageQualityDegradation'] !=''">
		   <eop:imageQualityDegradation uom="%"><xsl:apply-templates select="attribute[@id='imageQualityDegradation']"/></eop:imageQualityDegradation>
		</xsl:if>		
		<xsl:if test="attribute[@id='imageQualityStatus'] !=''">
		   <eop:imageQualityStatus><xsl:apply-templates select="attribute[@id='imageQualityStatus']"/></eop:imageQualityStatus>
		</xsl:if>
		<xsl:if test="attribute[@id='imageQualityDegradationTag'] !=''">
		   <eop:imageQualityDegradationTag><xsl:apply-templates select="attribute[@id='imageQualityDegradationTag']"/></eop:imageQualityDegradationTag>
		</xsl:if>		
		<xsl:if test="attribute[@id='imageQualityReportURL'] !=''">
		   <eop:imageQualityReportURL><xsl:apply-templates select="attribute[@id='imageQualityReportURL']"/></eop:imageQualityReportURL>
		</xsl:if>
       <!--eop:imageQualityDegradationTag codeSpace="urn:eop:SEN1:QualityDegradationTag">PLATFORM_POINTING</eop:imageQualityDegradationTag-->
       <eop:processing>
		<xsl:if test="attribute[@id='processingMode'] !=''">
		   <eop:ProcessingInformation>
				<eop:processingMode><xsl:apply-templates select="attribute[@id='processingMode']"/></eop:processingMode>			   
		   </eop:ProcessingInformation>
		</xsl:if>
       </eop:processing>
		<xsl:if test="attribute[@id='productGroupId'] !=''">
		   <eop:productGroupId><xsl:apply-templates select="attribute[@id='productGroupId']"/></eop:productGroupId>
		</xsl:if>
		<xsl:for-each select="attribute[substring-before(@id,'-')='add']">
			<eop:vendorSpecific>
				<eop:SpecificInformation>
					<eop:localAttribute><xsl:value-of select="substring-after(@id,'-')"/></eop:localAttribute>
					<eop:localValue><xsl:apply-templates select="."/></eop:localValue>
				</eop:SpecificInformation>
			</eop:vendorSpecific>
		</xsl:for-each>
     </eop:EarthObservationMetaData>
   </eop:metaDataProperty>
 </sar:EarthObservation>
#end
</rep:metadataReport>
	</xsl:template>
<xsl:template match="generalConstant ">
#set( $<xsl:value-of select="@name" /> = "<xsl:value-of select="." />" )
</xsl:template>
<xsl:template match="attribute">
<xsl:apply-templates select="*"/>
</xsl:template>
<xsl:template match="defaultValue">
	<xsl:value-of select="." />
</xsl:template>
<xsl:template match="indexFieldName">$metadata.<xsl:value-of select="." /></xsl:template>
<xsl:template match="formula">
	<xsl:value-of select="." />
</xsl:template>
<xsl:template name="extract">
	<xsl:param name="attribute"/>	
	<xsl:choose>
		<xsl:when test="$attribute/indexFieldName != ''">$<xsl:value-of select="$attribute/indexFieldName" /></xsl:when>
		<xsl:otherwise>
			<xsl:apply-templates select="."/>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>

</xsl:transform>
